
- product:
  id: product1
  name: ห่อหมกปลาทะเลสูตรโบราณ
  title: ร้านห่อหมกผู้ใหญ่ณะ @บ้านนาเกลือ
  discription: ห่อหมกทะเลสูตรโบราณ ขายมาสามรุ่นอายุ ห่อละ 25 บาท
  img: "../images/product/product1.png"
  url:
  contact: 081-809-0968
  owner: คุณอรุณี
  cat: OTOP อาหาร
  location: ตลาดเก่านาเกลือ

- product:
  id: product2
  name: เจ้กานดา กรอบเค็ม
  title: เจ้กานดา กรอบเค็ม
  discription: ขนมกรอบเค็ม ราคากล่องละ 35 บาท (180 กรัม) พิเศษซื้อ 3 กล่อง 100 บาท
  img: "../images/product/product2.png"
  url:
  contact: 089-834-7257
  owner: เจ้กานดา
  cat: OTOP ขนม
  location: บ้านนาเกลือ

- product:
  id: product3
  name: แจงลอน
  title: แจงลอนกุ้ง
  discription: แจงลอนกุ้ง ไม้ละ 10 บาท
  img: "../images/product/product3.png"
  url:
  contact: 093-983-7176
  owner: คุณวลีพร
  cat: OTOP อาหาร
  location: ชุมชนตลาดเก่า ตรงข้ามออมสินนาเกลือ ข้างร้านก๊วยเตี๋ยวสองบัณฑิต

- product:
  id: product4
  name: พริกย่าง
  title: พริกย่างทรงเครื่อง ไส้หมู-ไส้ไก่
  discription: พริกย่างทรงเครื่อง ไส้หมู-ไส้ไก่  กล่องละ 50 บาท (พริก 4 เม็ด), 100 บาท (พริก 8 เม็ด)
  img: "../images/product/product4.png"
  url:
  contact: 062-615-5983
  owner: คุณโจ๊ก
  cat: OTOP อาหาร
  location: ปากซอย 9 นาเกลือ ตรงข้ามร้านนำชัยอิเล็กโทรนิค 2 (สหพันธ์)

- product:
  id: product5
  name: น้ำปลาหวาน
  title: น้ำปลาหวาน แจ๋วแหวว
  discription: น้ำปลาหวานเครื่องแน่น ราคากระปุกละ 100 บาท (380 กรัม)
  img: "../images/product/product5.png"
  url:
  contact: 090-463-4565
  owner: พี่ธิดาวรรณ์
  cat: OTOP ของว่าง
  location: บ้านนาเกลือ

- product:
  id: product6
  name: ทอดมันปู
  title: เจ้เอื้อง ปูม้าต้ม ปูม้าแกะ ทอดมันปู
  discription: ทอดมันปู จากปลาอินทรีย์แท้ไม่ผสมแป้ง ถุงละ 100 บาท (3 ขีด) , ปูม้าต้ม-ปูม้าแกะ
  img: "../images/product/product6.png"
  url:
  contact: 081-779-4943
  owner: พี่เอื้อง
  cat: OTOP อาหาร
  location: หลังตลาดนาเกลือ

- product:
  id: product7
  name: ขนมเปียกปูนใบเตย
  title: ร้านเขมาภิรักษ์ มรดกไทย
  discription: ขนมเปียกปูนใบเตยและวุ้นใบเตย จำหน่ายเป็นถุง ถุงละ 15 บาท และมีแบบถาด เปียกปูนใบเตย ถาดละ 250 บาท  วุ้นใบเตยถาดละ 300 บาท
  img: "../images/product/product7.png"
  url:
  contact: 087-783-6673
  owner: ร้านเขมาภิรักษ์
  cat: OTOP ขนม
  location: หน้าตลาดเก่านาเกลือ

- product:
  id: product8
  name: ข้าวเหนียวมะม่วง
  title: ข้าวเหนียวมะม่วง คุณติ๋ว ลานโพธิ์
  discription: ข้าวเหนียวมูล กิโลกรัมละ 160 บาท มะม่วงสุกมี 3 ราคา - 100, 120, 150 บาทต่อ 1 กิโลกรัม แล้วแต่ฤดูกาล
  img: "../images/product/product8.png"
  url:
  contact: 081-8024112
  owner: คุณจริยา
  cat: OTOP ขนม
  location: หัวมุมหน้าตลาดลานโพธิ์

- product:
  id: product9
  name: ลูกชิ้นปลาป้าบล
  title: ลูกชิ้นปลาอินทรีย์ป้าบล
  discription: ลูกชิ้นปลาอินทรีย์แท้เจ้าเก่าดั้งเดิม ราคา ไม้ละ 10 บาท (มีลูกชิ้นปลาสดจำหน่ายแบบส่ง)
  img: "../images/product/product9.png"
  url: 064-7756311
  contact: 094-875-8926
  owner: คุณนิจ
  cat: OTOP อาหาร
  location: หน้าตลาดเก่านาเกลือ ข้าง7-11

- product:
  id: product10
  name: ขนมจีนน้ำพริก
  title: พี่นงเยาว์ ขนมจีนน้ำพริกน้ำยาปู
  discription: ขนมจีนน้ำพริกน้ำยาปู ชามละ 40 บาท, น้ำพริกลงเรือกล่องละ 40 บาท
  img: "../images/product/product10.png"
  url:
  contact: 095-175-3295
  owner: คุณนงเยาว์
  cat: OTOP อาหาร
  location: บ้านนาเกลือ