- product:
  name: ห่อหมกปลาทะเลสูตรโบราณ
  discription:
  img:
  url:
  contact: 081-809-0968 
  owner: พี่แอนนี่
  cat: OTOP อาหาร
- product:
  name: เจ้กานดา กรอบเค็ม
  discription:
  img:
  url:
  contact: 089-834-7257
  owner: เจ้กานดา
  cat: OTOP ขนม
- product:
  name: แจงลอน
  discription:
  img:
  url:
  contact: 093-9837176
  owner: พี่สุนีย์
  cat: OTOP อาหาร
- product:
  name: พริกย่าง
  discription:
  img:
  url:
  contact: 062-6155983 
  owner: พี่คมกริฤธิ์
  cat: OTOP อาหาร
- product:
  name: น้ำปลาหวาน
  discription:
  img:
  url:
  contact: 090-463-4565
  owner: พี่ธิดาวรรณ์
  cat: OTOP ของว่าง
- product:
  name: ทอดมันปู
  discription:
  img:
  url:
  contact: 081-779-4943 
  owner: พี่เอื้อง
  cat: OTOP อาหาร
- product:
  name: ขนมเปียกปูนใบเตย
  discription:
  img:
  url:
  contact: 087-783-6673 
  owner: ร้านเขมาภิรักษ์
  cat: OTOP ขนม
- product:
  name: ข้าวเหนียวมะม่วง
  discription:
  img:
  url:
  contact: 081-8024112 
  owner: พี่จริยา
  cat: OTOP ขนม
- product:
  name: ลูกชิ้นปลาป้าบล
  discription:
  img:
  url:
  contact: 094-875-8926 , 064-7756311
  owner: เจ้นิจ
  cat: OTOP อาหาร
- product:
  name: ขนมจีนน้ำพริก
  discription:
  img:
  url:
  contact: 095-175-3295
  owner: ป้านงเยาว์
  cat: OTOP อาหาร